"""Compatibility exports for the T14 treatment comparison module."""

from .comparison import (
    DeterminismMismatch,
    DeterminismReport,
    PairAudit,
    PairComparisonRunner,
    PairedComparisonRunner,
    PairedMetric,
    PairedReplayResult,
    PairedScoreView,
    ResourceDelta,
    StrategyAudit,
    StrategyRunReport,
    T14Config,
    T14Report,
    TreatmentAdapter,
    TreatmentComparisonReport,
    TreatmentComparisonRunner,
    TreatmentConfig,
    VisibilityAuditor,
    check_determinism,
    compare_treatments,
    run_t14_comparison,
    verify_determinism,
)

__all__ = [
    "DeterminismMismatch",
    "DeterminismReport",
    "PairAudit",
    "PairComparisonRunner",
    "PairedComparisonRunner",
    "PairedMetric",
    "PairedReplayResult",
    "PairedScoreView",
    "ResourceDelta",
    "StrategyAudit",
    "StrategyRunReport",
    "T14Config",
    "T14Report",
    "TreatmentAdapter",
    "TreatmentComparisonReport",
    "TreatmentComparisonRunner",
    "TreatmentConfig",
    "VisibilityAuditor",
    "check_determinism",
    "compare_treatments",
    "run_t14_comparison",
    "verify_determinism",
]
